// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace POCO
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the loaidichvu table.
    /// </summary>
	[Table("loaidichvu")]
	public partial class Loaidichvu
	{
		[Key]
		public virtual long maloai { get; set; }
		public virtual string tenloai { get; set; }
		public virtual IEnumerable<Dichvu> Dichvus { get; set; }
	}
}