// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace Models.POCO
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the booking_details table.
    /// </summary>
	[Table("booking_details")]
	public partial class BookingDetails
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int Booking_id { get; set; }
		public virtual int Room_id { get; set; }
		public virtual int NumberOfPeople { get; set; }
		public virtual double Amount { get; set; }
		public virtual DateTime? DateOfRentStart { get; set; }
		public virtual DateTime? DateOfRentEnd { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual DateTime ModifiedAt { get; set; }
		public virtual DateTime? DeletedAt { get; set; }
		public virtual bool hasForeigner { get; set; }
		public virtual int? Status { get; set; }
		public virtual Booking Booking { get; set; }
		public virtual Room Room { get; set; }
		public virtual BookingStatus BookingStatus { get; set; }
		public virtual IEnumerable<ServiceDetails> ServiceDetails { get; set; }
	}
}