// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace Models.POCO
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the customers table.
    /// </summary>
	[Table("customers")]
	public partial class Customer
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string FullName { get; set; }
		public virtual DateTime? DOB { get; set; }
		public virtual string IdentityCard { get; set; }
		public virtual string Phone { get; set; }
		public virtual bool isForeigner { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual DateTime ModifiedAt { get; set; }
		public virtual int? DeletedAt { get; set; }
		public virtual IEnumerable<Booking> Bookings { get; set; }
	}
}