// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace Models.POCO
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the room_state table.
    /// </summary>
	[Table("room_state")]
	public partial class RoomState
	{
		[Key]
		public virtual int RoomID { get; set; }
		public virtual int BookingID { get; set; }
		public virtual Booking Booking { get; set; }
		public virtual Room Room { get; set; }
	}
}