// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

namespace Models.POCO
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the service_details table.
    /// </summary>
	[Table("service_details")]
	public partial class ServiceDetails
	{
		public virtual int ServiceDetailsID { get; set; }
		public virtual int BookDetailID { get; set; }
		public virtual int ServiceID { get; set; }
		public virtual int Price { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual int Number { get; set; }
		public virtual BookingDetails BookingDetails { get; set; }
		public virtual Service Service { get; set; }
	}
}